# -*- coding: utf-8 -*-
"""yolov9_maintrain_alpha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BI-As6ACWUgr2V_0BmeTC0cx8LS0ix53

#import roboflow datasets
"""

!pip install YOLOv9
!apt install git
!git clone https://github.com/WongKinYiu/yolov9.git
!pip install -r ./yolov9/requirements.txt


from sklearn.model_selection import train_test_split
from glob import glob

import os
import shutil
from google.colab import drive
drive.mount('/content/drive')

# Setup directory paths
base_path = '/content/drive/MyDrive/dataset'
run_folder_path = os.path.join(base_path, 'run')
yolov9_source = '/content/yolov9'
yolov9_destination = os.path.join(run_folder_path, 'yolov9')

# Ensure the run directory exists
os.makedirs(run_folder_path, exist_ok=True)
print("Directory 'run' checked/created successfully")

# Move the YOLOv9 folder
shutil.move(yolov9_source, yolov9_destination)
print("YOLOv9 directory moved successfully")


# Function to prepare training and validation datasets
def prepare_datasets(image_dir, mask_dir):
    image_paths = glob(os.path.join(image_dir, '*.jpg'))
    mask_paths = glob(os.path.join(mask_dir, '*.txt'))
    dataset = list(zip(image_paths, mask_paths))
    train_data, val_data = train_test_split(dataset, test_size=0.2, random_state=42)
    return train_data, val_data

train_data, val_data = prepare_datasets('/content/drive/MyDrive/dataset/train_img',
                                        '/content/drive/MyDrive/dataset/train_mask')

# Save dataset paths to text files
def save_dataset_paths(data, filepath):
    with open(filepath, 'w') as f:
        for img_path, mask_path in data:
            f.write(f"{img_path} {mask_path}\n")

save_dataset_paths(train_data, '/content/drive/MyDrive/dataset/train.txt')
save_dataset_paths(val_data, '/content/drive/MyDrive/dataset/val.txt')

!python /content/drive/MyDrive/dataset/run/yolov9/yolov9/train.py --img 256 --batch 16 --epochs 50 \
    --data /content/drive/MyDrive/dataset/data.yaml \
    --cfg /content/drive/MyDrive/dataset/run/yolov9/models/detect/yolov9.yaml \
    --weights /content/drive/MyDrive/dataset/yolov9-c-converted.pt --name yolov9_training


